server:
  port: 0
#  port: ${random.int(50000,50001)}
#  address: 127.0.0.1

spring:
  application:
    name: user-service
  #  zipkin:
  #    base-url: http://127.0.0.1:9411
  #    enabled: true
  #  sleuth:
  #    sampler:
  #      probability: 1.0

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://3.38.147.68:3306/mydb
      username: root
      password: test1357

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 12345

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  #    prefer-ip-address: true
  #    ip-address: ${server.address}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true

greeting:
  message: Welcome to the Simple E-commerce.

logging:
  level:
    com.example.userservice.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus

token:
  expiration_time: 86400000
  secret: user_token